### ISSUE TITLE
2.0.3 crashes node-red

### ISSUE THREAD

**Issue by andreypopov** [igdr/node-red-contrib-xiaomi-smart-devices#18]
after installing 2.0.3 loop reboot

`13 May 06:11:43 - [info] Started flows
13 May 06:11:43 - [red] Uncaught Exception:
13 May 06:11:43 - Error: bind EADDRINUSE 0.0.0.0:9898
at Object.exports._errnoException (util.js:1024:11)
at exports._exceptionWithHostPort (util.js:1047:20)
at _handle.lookup (dgram.js:242:18)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
nodered.service: main process exited, code=exited, status=1/FAILURE
Unit nodered.service entered failed state.
nodered.service holdoff time over, scheduling restart.
Stopping Node-RED graphical event wiring tool....
Starting Node-RED graphical event wiring tool....`

**Comment by igdr** [comment]
which IP address did you set to the gateway node?

**Comment by andreypopov** [comment]
> which IP address did you set to the gateway node?

192.168.1.50 - and it was not saved, I had blank fields. Then I updated to 2.0.3

**Comment by igdr** [comment]
could you try restarting the server with Node-Red or kill the process which keeps 0.0.0.0:9898 and try again?

**Comment by andreypopov** [comment]
> could you try restarting the server with Node-Red or kill the process which keeps 0.0.0.0:9898 and try again?

I tried to reboot, still infinity restart loop. When I uninstalled your package - node-red works.

**Comment by igdr** [comment]
could you export your flow, I will try with your configuration

**Comment by andreypopov** [comment]
hm, I cant, when I save gateway config node-red crashes.

13 May 09:43:25 - Error: bind EADDRINUSE 0.0.0.0:9898
possible that openhab listening this address too and it cause this error

**Comment by igdr** [comment]
Do you use Node-Red and OpenHab with Xiaomi bindings on the same host machine?

**Comment by andreypopov** [comment]
yeah..

**Comment by igdr** [comment]
I think that is a problem, cause they both try to establish a connection to the same address and port.  I set up Node-Red and OpenHab to different raspberrypis.

**Comment by igdr** [comment]
No activity, so I close this issue
